#ifndef INNSMOUTH_GRAPHICS_TYPES_H
#define INNSMOUTH_GRAPHICS_TYPES_H

#include <volk/volk.h>
#include <vma/vk_mem_alloc.h>
#include "innsmouth/graphics/core/graphics_structures.h"

namespace Innsmouth {

AccessMask2 GetAccessMask(ImageLayout layout);
ImageAspectMask GetAspectMask(Format format);

bool HasBits(VkFlags supported_mask, VkFlags requiered_mask);
bool NotBits(VkFlags supported_mask, VkFlags requiered_mask);

enum class AllocationCreateMaskBits {
  E_DEDICATED_MEMORY_BIT = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT,
  E_NEVER_ALLOCATE_BIT = VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT,
  E_MAPPED_BIT = VMA_ALLOCATION_CREATE_MAPPED_BIT,
  E_UPPER_ADDRESS_BIT = VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT,
  E_DONT_BIND_BIT = VMA_ALLOCATION_CREATE_DONT_BIND_BIT,
  E_WITHIN_BUDGET_BIT = VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT,
  E_CAN_ALIAS_BIT = VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT,
  E_HOST_ACCESS_SEQUENTIAL_WRITE_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,
  E_HOST_ACCESS_RANDOM_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT,
  E_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT,
  E_STRATEGY_MIN_MEMORY_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
  E_STRATEGY_MIN_TIME_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
  E_STRATEGY_MIN_OFFSET_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT
};

using AllocationCreateMask = Mask<AllocationCreateMaskBits>;

} // namespace Innsmouth

#endif // INNSMOUTH_GRAPHICS_TYPES_H